APPLICATION_NAME: "test_generator"

server:
  port: 8000


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: myusername
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true
#${DB_USERNAME}