APPLICATION_NAME: "test-generator"

server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true

  security:
    oauth2:
      client:
        registration:
          test-generator:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid, profile, roles
            redirect-uri: http://localhost:8080/login/oauth2/code/testgenerator
        provider:
          test-generator:
            issuer-uri: http://localhost:8080/realms/testgeneratorapp

      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/testgeneratorapp/protocol/openid-connect/certs
